name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CR_URI: gitlab-cicd.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.CLOUDRU_ID_LOGIN }}
          password: ${{ secrets.KEY_SECRET_PASS }}
          
      - name: NodeJS - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapinodejs:${{ github.sha }}
          file: ./Dockerfile
          context: ./
