name: Build Docker Image and Push to Evolution Artifact Registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CR_URI: gitlab-cicd.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.CLOUDRU_ID_LOGIN }}
          password: ${{ secrets.KEY_SECRET_PASS }}

      - name: .NET - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapidotnet:${{ github.sha }}
          file: ./restapi-dotnet/Dockerfile
          context: ./restapi-dotnet
          
      - name: NodeJS - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapinodejs:${{ github.sha }}
          file: ./cicd-cloudru/Dockerfile
          context: ./cicd-cloudru
          
      - name: Python - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapipython:${{ github.sha }}
          file: ./restapi-python/Dockerfile
          context: ./restapi-python

      - name: Go - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapigo:${{ github.sha }}
          file: ./restapi-go/Dockerfile
          context: ./restapi-go
